

GET http://localhost:3000/

###
GET http://localhost:3000/api

###
POST http://localhost:3000/api/post
Content-Type: application/json

{
  "some": "vonhucong",
  "for": "you"
}

###
POST http://localhost:3000/create-user
Content-Type: application/json

{
  "username": "nguyenvana",
  "email": "a@gmail.com"
}

###
GET http://localhost:3000/get-user
    # ?userID=cfd189cf-ec3a-4fe4-ba8a-40f2516f2604
    # &username=nguyenvana
    # &email=vncong1108@gmail.com



###
POST http://localhost:3000/update-user
Content-Type: application/json

{
  "id": "e27cc82c-9eca-40cf-90ce-af704a2f21e4",
  "email": "abcd@gmail.com"
}



